# Generated by Django 4.0.3 on 2022-04-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100)),
                ('title', models.CharField(default=' ', max_length=40)),
                ('email', models.CharField(default=' ', max_length=60)),
                ('phone', models.CharField(default=' ', max_length=15)),
                ('pic', models.URLField()),
                ('heading', models.CharField(default=' ', max_length=120, null=True)),
                ('website', models.URLField(null=True)),
                ('bio', models.TextField(default=' ', null=True)),
                ('edited', models.BooleanField(default=False, null=True)),
                ('research', models.ManyToManyField(to='display.researchcategory')),
            ],
        ),
    ]
