# Generated by Django 4.0.3 on 2022-04-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymodel',
            name='customIMG',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='facultymodel',
            name='pic',
            field=models.URLField(default='https://odu.edu/content/dam/odu/faculty-staff/person-placeholder-2015.png/_jcr_content/renditions/cq5dam.thumbnail.319.319.png'),
        ),
    ]
