# Generated by Django 4.0.3 on 2022-04-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_facultymodel_customimg_alter_facultymodel_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymodel',
            name='address',
            field=models.TextField(default=' ', null=True),
        ),
    ]
