# Generated by Django 4.0.3 on 2022-04-19 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_facultymodel_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultymodel',
            old_name='research',
            new_name='researchTypes',
        ),
    ]
