# Generated by Django 4.0.4 on 2022-06-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0005_remove_facultymodel_customimg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymodel',
            name='hasCustomPic',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
